using System;

namespace Alpha.Models.Alpha;

public class BensBetha
{
    public int id { get; set; }
    public string id_cloud { get; set; }
    public int i_bem { get; set; }
    public int? i_conta { get; set; }
    public int? i_custo { get; set; }
    public int? i_unidade { get; set; }
    public int? i_respons { get; set; }
    public int? i_fornec { get; set; }
    public int? i_tipo_natur { get; set; }
    public string descricao { get; set; }
    public string data_aquis { get; set; }
    public string documento { get; set; }
    public string fornecedor { get; set; }
    public decimal? valor_aquis { get; set; }
    public int? i_moeda { get; set; }
    public decimal? valor_original { get; set; }
    public decimal? valor_reav { get; set; }
    public decimal? valor_depr { get; set; }
    public string tipo_aquis { get; set; }
    public string data_garant { get; set; }
    public string data_proxrev { get; set; }
    public int? nr_empenho { get; set; }
    public string situacao { get; set; }
    public string historico { get; set; }
    public string uso { get; set; }
    public string est_cons { get; set; }
    public int? ano_empenho { get; set; }
    public int? i_ano_proc { get; set; }
    public int? i_processo { get; set; }
    public string data_processo { get; set; }
    public string liquid_compras { get; set; }
    public int? codigo_localizacao { get; set; }
    public int? codigo_intervencao { get; set; }
    public string numero_placa { get; set; }
    public string numero_termo { get; set; }
    public string data_termo { get; set; }
    public string data_prazo { get; set; }
    public decimal? valor_residual { get; set; }
    public decimal? valor_depreciavel { get; set; }
    public string dt_inicio_deprec { get; set; }
    public decimal? perc_deprec_anual { get; set; }
    public string utiliza_exprecnatur { get; set; }
    public int? i_localiz_fis { get; set; }
    public int? i_entidades { get; set; }
    public int? i_detalhamentos_bens { get; set; }
    public int? utilizacao { get; set; }
    public int? origem { get; set; }
    public int? i_tipo_documento { get; set; }
    public int? vida_util { get; set; }
    public int? id_tipo_bem { get; set; }
    public int? id_grupo_bem { get; set; }
    public int? id_especie_bem { get; set; }
    public int? id_tipo_utilizacao { get; set; }
    public int? id_tipo_aquisicao { get; set; }
    public int? id_fornecedor { get; set; }
    public int? id_responsavel { get; set; }
    public int? id_estado_conservacao { get; set; }
    public int? id_tipo_comprovante { get; set; }
    public int? id_organograma { get; set; }
    public int? id_localizacao_fisica { get; set; }
    public int? id_metodo_depreciacao { get; set; }
}

public class BensMercato
{
    public int codigo { get; set; }
    public string descricao { get; set; }
    public string tp_recurso_cod { get; set; }
    public int? tp_origem_cod { get; set; }
    public int? lic_metodo_cod { get; set; }
    public string tp_avaliacao_numero { get; set; }
    public int? tp_classificacao_cod { get; set; }
    public int? tp_empenho_cod { get; set; }
    public string tp_lei { get; set; }
    public int? tp_lei_num { get; set; }
    public DateTime? tp_lei_data { get; set; }
    public string tipo { get; set; }
    public int? local_cod { get; set; }
    public string unidade_cod { get; set; }
    public int? plaqueta { get; set; }
    public string processo_num { get; set; }
    public int? processo_ano { get; set; }
    public int? fornecedor_cod { get; set; }
    public int? notafiscal { get; set; }
    public string nfiscalserie { get; set; }
    public DateTime? nfdata { get; set; }
    public decimal? nfvalor { get; set; }
    public DateTime? tombamento_data { get; set; }
    public DateTime? alienacao_data { get; set; }
    public DateTime? garantia_data { get; set; }
    public decimal? avaliacao_atual_valor { get; set; }
    public DateTime? avaliacao_atual_data { get; set; }
    public int? empenho_num { get; set; }
    public int? empenho_ano { get; set; }
    public int? lei_numero { get; set; }
    public int? seguro_fornecedor_cod { get; set; }
    public string seguro_apolice { get; set; }
    public DateTime? seguro_apolice_data { get; set; }
    public DateTime? seguro_apolice_venc { get; set; }
    public int? atual_status_cod { get; set; }
    public int? aquisicao_status_cod { get; set; }
    public string user_cadastro { get; set; }
    public DateTime? data_cadastro { get; set; }
    public TimeSpan? hora_cadastro { get; set; }
    public DateTime? data_atualiza { get; set; }
    public TimeSpan? hora_atualiza { get; set; }
    public string user_atualiza { get; set; }
    public int? subgrupo_bens_cod { get; set; }
    public int? subgrupo_pro_cod { get; set; }
    public string produto_cod { get; set; }
    public string tp_avaliacao { get; set; }
    public int? baixado { get; set; }
    public DateTime? data_baixa { get; set; }
    public int? comodato { get; set; }
    public string obs_aq2 { get; set; }
    public string obs_aquisicao { get; set; }
    public int? atual_status_cod_avalia { get; set; }
    public decimal? seguro_valor { get; set; }
    public string raca { get; set; }
    public string cor { get; set; }
    public DateTime? data_nasc { get; set; }
    public decimal? vlr_residual { get; set; }
    public string id_cloud { get; set; }
}